services:
  fastapi:
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .dev.env   
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  worker:
    build:
      context: ./backend
      target: dev
    depends_on:
      - redis
    volumes:
      - ./backend/app:/app/app
    env_file:
      - .dev.env
    command: poetry run python -m app.ingest_runner

  redis:
    image: "redis:8.0.3-bookworm"
    ports:
      - "6379:6379"
  
  mock_open311:
    build:
      context: ./mock_open311
    ports:
      - "8081:80"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      - fastapi
    volumes:
      - ./frontend:/app
      - /app/node_modules