services:
  fastapi:
    build:
      context: ./backend
      target: dev
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    volumes:
      - ./backend/app:/app/app
    command: poetry run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  redis:
    image: "redis:8.0.3-bookworm"
    ports:
      - "6379:6379"