services:
  fastapi:
    build:
      context: ./backend
      target: prod
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    env_file:
      - .prod.env
    depends_on:
      - redis

  worker:
    build:
      context: ./backend
      target: prod
    command: python -m app.ingest_runner
    env_file:
      - .prod.env
    depends_on:
      - redis

  redis:
    image: "redis:8.0.3-bookworm"
    expose:
      - "6379"

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - fastapi
