from enum import Enum

class RequestFlag(str, Enum):
    VALID = 'VALID'
    CATEGORY_MISMATCH = 'CATEGORY_MISMATCH'
    IMAGE_MISMATCH = 'IMAGE_MISMATCH'
    OVERSTATED_SEVERITY = 'OVERSTATED_SEVERITY'
    UNCLEAR = 'UNCLEAR'
    DUPLICATE = 'DUPLICATE'
    SPAM = 'SPAM'
    MISSING_INFO = 'MISSING_INFO'
    MISCLASSIFIED_LOCATION = 'MISCLASSIFIED_LOCATION'
    NON_ISSUE = 'NON_ISSUE'
    OTHER = 'OTHER'
