from enum import Enum

class RequestFlag(str, Enum):
    VALID = 'VALID'
    WRONG_CATEGORY = 'WRONG_CATEGORY'
    WRONG_LOCATION = 'WRONG_LOCATION'
    IMAGE_CONFLICT = 'IMAGE_CONFLICT'
    SEVERITY_OVERSTATED = 'SEVERITY_OVERSTATED'
    INSUFFICIENT_INFO = 'INSUFFICIENT_INFO'
    INVALID_REPORT = 'INVALID_REPORT'
